version: '3'
services:
  todotests:
    image: todotests
    restart: on-failure
    depends-on:
    - todofront
    - todoback
    environment:
    - FRONT_HOST="todofrontend"
  todofront:
    image: todofrontend
    restart: on-failure
    ports:
    - 3000:80
    depends-on:
     - todoback
    environment:
    - REACT_APP_API_HOST="todobackend"
  todoback:
    image: todobackend
    restart: on-failure
    ports:
    - 3001:80
  